ddp:
    master_addr: "localhost"
    master_port: "29601" #"29600" #"29501" #"29500"
    num_devices: 1

rlbench:
    task_name: "multi"
    tasks: [put_money_in_safe] #[put_money_in_safe] #[open_drawer] #,slide_block_to_color_target]
    demos: 10 #100
    demo_path: $PERACT_ROOT/data/val  #/my/demo/path #/home/bobwu/UQ/peract_headless/peract_reliability/data/val #
    episode_length: 25
    cameras: [front,left_shoulder,right_shoulder,wrist]
    camera_resolution: [128, 128]
    scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
    include_lang_goal_in_obs: True

replay:
    batch_size: 8
    timesteps: 1
    prioritisation: False
    task_uniform: True # uniform sampling of tasks for multi-task buffers
    use_disk: True
    path: '/tmp/arm/replay' # only used when use_disk is True.
    max_parallel_processes: 32

framework:
    log_freq: 100
    save_freq: 100
    train_envs: 1
    replay_ratio: ${replay.batch_size}
    transitions_before_train: 200
    tensorboard_logging: True
    csv_logging: True
    training_iterations: 40000
    gpu: 0
    env_gpu: 0
    logdir: '/tmp/arm_test/'
    logging_level: 20 # https://docs.python.org/3/library/logging.html#levels
    seeds: 1
    start_seed: 0
    load_existing_weights: True #FIXED #False
    num_weights_to_keep: 60 # older checkpoints will be deleted chronologically
    num_workers: 0
    record_every_n: 5

scaler:
    type: 'vector'

temperature:
    temperature_training: False
    temperature_training_iter: 1000
    temperature_use_hard_temp: True #False
    temperature_hard_temp: 3 #3 #3 #1.5 #3
    load_indiv_temp: False
    # 3 for put_money_in_safe
    # 5.5 for push buttons
    # 1.5 for open_drawer
    temp_log_root: '/home/bobwu/shared/temp_train_5tasks_0'

vector:
    vector_training: False
    vector_training_iter: 1000
    vector_log_root: '/home/bobwu/shared/vector_train_5tasks_0'

risk:
  alpha1: 1
  alpha2: 1
  alpha3: 1000
  alpha4: 1000
  tau: 5
  trans_conf_thresh: 1.0e-6
  rot_conf_thresh: 0.014 #1/72
  search_size: 20
  search_step: 2
  log_dir: /home/bobwu/shared/safe_action_new/ # /home/bobwu/shared/safe_action_conf100_set/
  enabled: False
defaults:
    - method: C2FARM

hydra:
    run:
        dir: ${framework.logdir}/${rlbench.task_name}/${method.name}
